Repository nextcloud/flow_notifications, pull requests merged in 2024-07, with the labels that each got.

#164 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#163 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#167 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#168 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#169 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#166 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#171 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#170 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#173 build(npm): bump requirement to 10 and update deps
  package-lock.json
  package.json
Labels: 3. to review

#174 build(packaging): update appstore-build-publish from templates
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#178 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#177 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#176 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#175 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
