Repository nextcloud/flow_notifications, pull requests merged in 2024-12, with the labels that each got.

#235 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#238 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#236 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#237 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#239 [stable30] ci: add ocp-approve-merge action
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  lib/Listener/RegisterOperationsListener.php.orig
Labels: 4. to release, backport-request

#242 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#244 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#247 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#248 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
