Repository nextcloud/flow_notifications, pull requests merged in 2025-04, with the labels that each got.

#293 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#295 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#294 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#289 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#299 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#297 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#298 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#302 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#305 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#307 ci: update github workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  psalm.xml
Labels: 3. to review

#306 fix: ensure to return an absolute icon url for client compatibility
  lib/Notification/Notifier.php
Labels: 3. to review, bug

#308 fix: adjust to workflowengine changes and register web component
  package-lock.json
  package.json
  src/main.js
  src/views/FlowNotify.vue
Labels: 3. to review, technical debt

#304 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#312 [stable31] ci: update github workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  psalm.xml
Labels: 3. to review

#303 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
