Repository nextcloud/flow_notifications, pull requests merged in 2025-05, with the labels that each got.

#315 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#314 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#317 build: remove more files from release tarball
  .nextcloudignore
Labels: 3. to review, backport-request

#321 build(Release): v1.10.2
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#322 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#323 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#324 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#328 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#327 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#331 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#329 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
